
"""
    ************************************************************************
    ***                                                                  ***
    ***                Source code generated by cl2py.pl                 ***
    ***                                                                  ***
    ***                        Please do not edit                        ***
    ***                                                                  ***
    ************************************************************************
"""
#!/usr/bin/python3 python3

# OPENCL LIBRARY
import pyopencl as cl

# VGL LIBRARYS
import vgl_lib as vl

#TO WORK WITH MAIN
import numpy as np

"""
    /** Erosion of src image by mask. Result is stored in dst image.

  */    
"""
elif vGlyph.func == 'vglClDilate':
    vglClDilate_img_input = getImageInputByIdName(vGlyph.glyph_id, 'img_input')
    vglClDilate_img_output = getImageInputByIdName(vGlyph.glyph_id, 'img_output')
    vl.vglCheckContext(vglClDilate_img_output, vl.VGL_CL_CONTEXT())
    vglClDilate(vglClDilate_img_input, vglClDilate_img_output, tratnum(vGlyph.lst_par[0].getValue()), np.uint32(vGlyph.lst_par[1].getValue()), np.uint32(vGlyph.lst_par[2].getValue()))
    GlyphExecutedUpdate(vGlyph.glyph_id, vglClDilate_img_output)
"""
    /** Erosion of src image by mask. Result is stored in dst image.

  */    
"""
elif vGlyph.func == 'vglClErode':
    vglClErode_img_input = getImageInputByIdName(vGlyph.glyph_id, 'img_input')
    vglClErode_img_output = getImageInputByIdName(vGlyph.glyph_id, 'img_output')
    vl.vglCheckContext(vglClErode_img_output, vl.VGL_CL_CONTEXT())
    vglClErode(vglClErode_img_input, vglClErode_img_output, tratnum(vGlyph.lst_par[0].getValue()), np.uint32(vGlyph.lst_par[1].getValue()), np.uint32(vGlyph.lst_par[2].getValue()))
    GlyphExecutedUpdate(vGlyph.glyph_id, vglClErode_img_output)
